const menuList = [
  { "title": "Ambience", "blocks": false, "items": true, "crafting": false },
  // { "title": "Artisan's Blocks", "blocks": true, "items": true, "crafting": true },
  // { "title": "Automaticraft", "blocks": true, "items": true, "crafting": true },
  // { "title": "Bedrock Recrafted", "blocks": true, "items": true, "crafting": true },
  // { "title": "Block Letters", "blocks": true, "items": true, "crafting": true },
  // { "title": "Boomerangs", "blocks": true, "items": true, "crafting": true },
  // { "title": "Bridge Cannon", "blocks": true, "items": true, "crafting": true },
  // { "title": "Cargo Craft", "blocks": true, "items": true, "crafting": true },
  // { "title": "Colorful Spiders", "blocks": true, "items": true, "crafting": true },
  // { "title": "Crimson Staff", "blocks": true, "items": true, "crafting": true },
  // { "title": "Displaydestal", "blocks": true, "items": true, "crafting": true },
  // { "title": "Distraction Dolls", "blocks": true, "items": true, "crafting": true },
  // { "title": "Domestic Mobs", "blocks": true, "items": true, "crafting": true },
  // { "title": "Drill Buddy", "blocks": true, "items": true, "crafting": true },
  // { "title": "Elemental Weapons", "blocks": true, "items": true, "crafting": true },
  // { "title": "Ender Sceptre", "blocks": true, "items": true, "crafting": true },
  // { "title": "Food!", "blocks": true, "items": true, "crafting": true },
  // { "title": "Generate and Duplicate", "blocks": true, "items": true, "crafting": true },
  // { "title": "Helpful Blocks", "blocks": true, "items": true, "crafting": true },
  // { "title": "Hybrid Slabs", "blocks": true, "items": true, "crafting": true },
  // { "title": "Item Bundler", "blocks": true, "items": true, "crafting": true },
  // { "title": "Laser Quarry", "blocks": true, "items": true, "crafting": true },
  // { "title": "Lodestone Pillars", "blocks": true, "items": true, "crafting": true },
  // { "title": "Mineral Signals", "blocks": true, "items": true, "crafting": true },
  // { "title": "Mini Mob-Grinder", "blocks": true, "items": true, "crafting": true },
  // { "title": "Mob Statues", "blocks": true, "items": true, "crafting": true },
  // { "title": "More Crops", "blocks": true, "items": true, "crafting": true },
  // { "title": "More Tnt", "blocks": true, "items": true, "crafting": true },
  // { "title": "More Turrets", "blocks": true, "items": true, "crafting": true },
  // { "title": "Ore Seeds", "blocks": true, "items": true, "crafting": true },
  // { "title": "Oresight", "blocks": true, "items": true, "crafting": true },
  // { "title": "Paint Bombs", "blocks": true, "items": true, "crafting": true },
  // { "title": "Potion Blocks", "blocks": true, "items": true, "crafting": true },
  // { "title": "Pottery", "blocks": true, "items": true, "crafting": true },
  // { "title": "Project: Beach", "blocks": true, "items": true, "crafting": true },
  // { "title": "Project: Flower Forest", "blocks": true, "items": true, "crafting": true },
  // { "title": "Project: Mushroom Island", "blocks": true, "items": true, "crafting": true },
  // { "title": "Quick Bunkers", "blocks": true, "items": true, "crafting": true },
  // { "title": "Rail Craft", "blocks": true, "items": true, "crafting": true },
  // { "title": "Recycle Craft", "blocks": true, "items": true, "crafting": true },
  // { "title": "Resourcefulness", "blocks": true, "items": true, "crafting": true },
  // { "title": "Rotated Planks", "blocks": true, "items": true, "crafting": true },
  // { "title": "Spawn Crafter", "blocks": true, "items": true, "crafting": true },
  // { "title": "Tankers", "blocks": true, "items": true, "crafting": true },
  // { "title": "Tatsulok", "blocks": true, "items": true, "crafting": true },
  // { "title": "The Variants", "blocks": true, "items": true, "crafting": true },
  // { "title": "Tipped Swords", "blocks": true, "items": true, "crafting": true },
  // { "title": "Topiary", "blocks": true, "items": true, "crafting": true },
  { "title": "Total Carnage", "blocks": true, "items": true, "crafting": true },
  { "title": "Useful Sides", "blocks": true, "items": false, "crafting": false },
  // { "title": "Useful Staffs", "blocks": true, "items": true, "crafting": true },
  // { "title": "Vanilla Figurines", "blocks": true, "items": true, "crafting": true },
  // { "title": "Villajars", "blocks": true, "items": true, "crafting": true },
  // { "title": "Xpiggy Bank", "blocks": true, "items": true, "crafting": true }
];