const addonsList = [
  {
    "dat_link": "https://link-hub.net/131911/ambience-dat",
		"res_link": "https://link-target.net/131911/ambience-res",
		"gallery": 4,
    "title": "Ambience",
		"desc": "This adds entities that emit sound. They spawn around the world and provides a simple immmersion addition",
    "full_desc": "This might be a small add-on but it adds aesthetics around 2 major biomes. The Forest (all variants except the tundra) has bird chirping noises now, especially the roofed forest. The Nether has creepy choir-like noises to give the player a more ominous feel.",
		"crafting": false,
		"blocks": false,
		"items": true,
		"entities": false,
		"structures": false
  },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Artisan's Blocks",
		// "desc": "This adds tons of decorative blocks. With over 1000 craftable blocks, you should be a able to decorate your world.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Automaticraft",
		// "desc": "This adds blocks that help you automate tasks. Adding solar panels, harvesters, absorbers, etc.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Bedrock 2.0",
		// "desc": "Mainly focusing on odd aspects of the game, this will add defensive villagers, underground monsters, and new aquatic life",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Bedrock Recrafted",
		// "desc": "This adds loot for almost every vanilla mob. It also features frequent natural disasters.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Better Behaviors",
		// "desc": "It might not be for everyone but this will add logical effects and consequences from holding certain items.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  {
    "dat_link": "https://link-target.net/131911/biome-box-dat",
		"res_link": "https://link-center.net/131911/biome-box-res",
		"gallery": 2,
    "title": "Biome Box",
		"desc": "Adds naturally spawning loot boxes filled with items related to the biomes they spawn in. Though they're an uncommon occurance, they may hold overpowered loot.",
    "full_desc": "Beginning to imagine to find the resources being spoonfed to the player in the form of a loot box found in their native biomes; that's the idea of the Biome Box add-on. This add-on will spawn rare boxes throughout the world filled with content native to the biome they spawn in. With so much as 22 boxes to find scattered around every major biome, seeing all of them in your base might cna be a big flex to make proving you travelled across those biomes. The boxes aren't structures and can be treated as entities, they don't have a fixed coordinate to spawn on so living in a biome may spawn more.",
		"crafting": false,
		"blocks": true,
		"items": false,
		"entities": false,
		"structures": false
  },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Biome Project: 0",
		// "desc": "The first contender of the BIOME series adds loads of custom mobs. It will help populate certain empty biomes with new content.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Block Letters",
		// "desc": "Adds flat character blocks in Enlish and Japanese, mainly taking inspiration from neon lights and allows you to decorate with block-sized letters",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Boomerangs",
		// "desc": "Adds new weapons that will return to you when thrown. Some can be used to nab items or even singe multiple enemies at once",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Bridge Cannon",
		// "desc": "Adds new equipment that builds bridges in front of the user. The barebones bridge is made of the same type of wood used to reload it.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Cargo Blocks",
		// "desc": "Adds decorative blocks meant for building huge crates and shipping containers. It also adds an automatic builder if you don't like building one manually.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Cargo Craft",
		// "desc": "Adds carts that let you store stuff. The carts can transport mobs, liquids, and chests.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Colorful Spiders",
		// "desc": "This will simply add new colorful variations of spiders. Each spider will drop silk based on their color which can be crafted into stiched silk.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Cosmetic Snowman",
		// "desc": "This adds new variations of snowmen when you shear the pumpkin off of a snow golem.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Crimson Staff",
		// "desc": "Adds Megumin's staff from KonoSuba. It will allow the user to cast a powerful explosion at a distance.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Decor++",
		// "desc": "Mainly adds decorative entities used in maps made by the same creator.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Displaydestal",
		// "desc": "This adds armor stand-like entities that can display your items.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Distraction Dolls",
		// "desc": "Adds throwable items that distract nearby entities and detontate after a few seconds. The user can change the skin of one of these items with their own",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Domestic Mobs",
		// "desc": "This'll add domesticated versions of vanilla livestock mobs. The domesticated versions will yield higher loot than their original counterparts.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Drill Buddy",
		// "desc": "This adds new machinery that helps the user drill holes. The size and deph of eah hole depends on the tier of upgrade",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Earth Banner",
		// "desc": "Adds the initial concept of a new pattern from Java Edition. This addon was made when the Globe banner pattern wasn't in Bedrock yet.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Elemental Weapons",
		// "desc": "Adds new weapons inspired by each natural element. With each unique ability a weapon offers, the weapons are crafted from runes found in chests.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Ender Sceptre",
		// "desc": "Adds a simple item where you teleport where your cursor points. You need to sacrifice your dragon egg trophy for it though.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Fist of Supremacy",
		// "desc": "Adds an overpowered weapon where it doubles its damage everytime you charge it. The final damage can reach higher than a billion!",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Food Fight!",
		// "desc": "Adds the ability for the player to throw food items. The damage of each food is based on the saturation points.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Food!",
		// "desc": "This will provide a whole new array of decorations that revolve around food. It combines three old outdated addons into a newer version as it bridges features together.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Generate and Duplicate",
		// "desc": "Adds machinery that helps generate raw resources and machinery that helps duplicate processed resources.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Grindstone",
		// "desc": "Adds a simple entity that repairs your equipment after interacting with it.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  {
    "dat_link": "https://link-center.net/131911/helpful-blocks-dat",
		"res_link": "https://direct-link.net/131911/helpful-blocks-res",
		"gallery": 3,
    "title": "Helpful Blocks",
		"desc": "Adds blocks with new mechanics that may help in automation and other aspects. Adding gates, conveyor belts, grinders, filters, etc.",
    "full_desc": "Industrially speaking, Minecraft is set in a time where technology clearly isn't around. This add-on provides you with more than 40 new blocks which allows you to burn, carry, and filter. The blocks have their own unique abilities however these blocks are supposed to be activated with redstone but that feature isn't possible yet!",
		"crafting": true,
		"blocks": true,
		"items": false,
		"entities": false,
		"structures": false
  },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Hybrid Slabs",
		// "desc": "Adds every possible combination of double slab blocks. They also feature a vertical orientation.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "ITEM BUNDLER",
		// "desc": "Adds an entity that lets you bundle up stacks of items into blocks. These blocks can be stacked up too so you can save up space.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Just Chairs",
		// "desc": "This adds new decorative entities that you can sit on. They come in a range of varieties taht should be able to suit any theme.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Just Lights",
		// "desc": "This adds new decorative entities that you can interact with. They come in a variety of themes and may fit most builds.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Laser Quarry",
		// "desc": "Adds an entity that fires a laser that digs underground. It's not really an original concept and is a really quick way to bore a hole through your world.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Lodestone Pillars",
		// "desc": "This will add an item that will let you teleport to the nearest pillar. The pillars are made from different kinds of stone and each item will teleport to the nearest pillar of the same type.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Maids & Butlers",
		// "desc": "This will add servants that follow you around your world. They can hunt mobs and cook items for you when interacted with certain items.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Mineral Signals",
		// "desc": "This will add an item that will generate beams of particles over vanilla ores. Each item will have their designated mineral and will generate the beam when used.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Minigen",
		// "desc": "Adds tiny versions of Naturally generated structures all over the world. They drop half thw amount of blocks that are used to build the original structure.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Mini Mob-grinder",
		// "desc": "Adds blocks that will generate loot from mobs. All you need is to give it a spawn egg of theob you want to grind.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Minitrees",
		// "desc": "This will add tiny trees spawnng around forests. They drop half the amount of their bigger counterparts.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Mob Blocks",
		// "desc": "Adds blocks that will instantly spawn mobs. It also allows you to use the /fill command to spawn mobs.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Mob Statues",
		// "desc": "Adds decorative entities that act like statues. They come in stone, iron, and gold. There are only statues for vanilla mobs.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Mob Yeet",
		// "desc": "This adds gloves that let you toss any mob. All you need to do is sneak near one and carry them over your head and stop sneaking to throw.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "More Crops",
		// "desc": "This adds new entities that act like crops to the game. It also adds new trees, decorative entities, and edible items.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "More Tnt",
		// "desc": "This adds a variety of new explosives into the game. It adds grenades, napalm, nukes, bazookas, and more.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "More Turrets",
		// "desc": "This adds new protective stationary entities. The have a range of ammo and you can even upgrade them as well.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Ore Seeds",
		// "desc": "This adds new items that let you infuse ores into other terrain blocks. It has a limited range but downright overpowered.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Oresight",
		// "desc": "This adds a new item that lets you see ores. The item will give you a temporary x-ray-like vision and let you see the ores.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Outdoor Escape",
		// "desc": "This adds new decorative entities themeed around camping. It adds tents, bonfires, log seats, etc.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Paint Bombs",
		// "desc": "Adds new items that let you paint dyed blocks without having to break them. The concept is simple, you throw a paint bomb at a dyed blck and it will convert it into the paint bomb's color.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Phantasy",
		// "desc": "Adds new mobs typically from the fantasy genre. Random monsters such as a big wolf and a sea monster are added.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Pool Party",
		// "desc": "Adds new decorative entities themed around water toys. It adds jetskis, swimming rings, and swimming beds.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Potion Blocks",
		// "desc": "This adds blocks that give their designated status effects when stepped on. The concept is simple, just add a flask of the effect you want on the block and interact with it.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Project: Beach",
		// "desc": "A part of the BIOME series, it upgrades the beach with new trees and crabs. It adds banana and coconut trees and their wood products.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Project: Flower Forest",
		// "desc": "A part of the BIOME series, it upgrades the flower forests with giant flowers and butterflies. You can collect the butterflies in a jar and display them.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Project: Mushroom Island",
		// "desc": "A part of the BIOME series, it upgrades the mushroom islands with new mushroom and mooshroom. There are many types of mushroom added in this addon and all f them can be sheared off of mooshrooms.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Quick Bunkers",
		// "desc": "This adds new tools that help you hide underground in an instant. Using a Quick Bunker will hide you 3 blocks underground surrounded by the blocks you used to craft the tool.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Recycle Craft",
		// "desc": "This adds a new entity tht allows you to burn items and turn them into ash. These ashes can be turned into decorative building blocks and are very cheap to make.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Rail Craft",
		// "desc": "This adds new de facto minecarts into the game. They're fake minecarts as they ride a true custom minecart and act as models. These are only for decorative purposes but can sill move on rails",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Resourcefulness",
		// "desc": "This adds new decorative variations of building blocks. You can access these new blocks using the stonecutter.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Road Stuff",
		// "desc": "This adds decorative entities themed around objects commonly found on roads. It adds signs, traffic cones, and more signs, signs and.. signs.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Rotated Planks",
		// "desc": "Adds vertical rotations of vanilla wooden planks. This is a very simple concept that was inspired by checker patterns.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Spawn Crafter",
		// "desc": "Adds a way for you to craft spawn eggs and mob spawners. You can craft equipment to take remnants from vanilla mobs and craft a spawn egg using them.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Tankers",
		// "desc": "Adds blocks that let you store liquids or anything a bucket may store except animals. The tankers can store up to 20 and can be stacked. Imagine carrying 1,280 buckets of water in one hand.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Tatsulok",
		// "desc": "Adds slopes or triangle blocks to the game. These decorative blocks behave like stairs and lets you smooth out any build.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Test Dummies",
		// "desc": "Adds decorative entities that can be tested on. Each dummy has their own feature and acts like the mob they represent, just stationary.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "The Variants",
		// "desc": "Adds more unique variants to vanilla mobs. There are new types of zombies, skeletons, creepers, and more.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Tipped Swords",
		// "desc": "Adds negative potion effects for swords. The tipped swords will apply its status effect when hitting an entity.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Topiary",
		// "desc": "Adds decorative variants of vanila leaves. They can get bushier over time and you can shear the excess leaves off. These new decorative blocks are not affected by decay.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  {
    "dat_link": "https://direct-link.net/131911/total-carnage-dat",
		"res_link": "https://direct-link.net/131911/total-carnage-res",
		"gallery": 10,
    "title": "Total Carnage",
		"desc": "Probably one of the most unforgiving addons to exist. It makes hell out of every dimension and definitely creates a challenge for every player.",
    "full_desc": "I think this is the addon that took me the longest to make. Almost 3 years in and finally completed it, the long awaited Carnage update! This new version of Carnage adds another 100 mobs into the game, most monsters have unique behaviors and their abilities range from puny to outright devastating! This new version adds a variety of new items, decorations, structures, and next time, biomes. Keep in mind that some monsters won't spawn naturally at the moment as I figure out how to make mobs who live in the void spawn. But nevertheless, this is definitely one of the addons of all time!",
		"crafting": true,
		"blocks": true,
		"items": true,
		"entities": true,
		"structures": true
  },
  {
    "dat_link": "https://direct-link.net/131911/useful-sides-dat",
		"res_link": "https://direct-link.net/131911/useful-sides-res",
		"gallery": 3,
    "title": "Useful Sides",
		"desc": "This adds new decorative blocks that uses unnoticed textures from the vanilla game. Most blocks in the game have more than one texture so this addon will provide those textures as plain blocks.",
    "full_desc": "Blocks have their own sides and it's a shame that we can't use them the way we want to all the time, so this add-on gives you that possibility! This add-on adds more than 200 blocks that uses almost every vanilla texture.",
		"crafting": true,
		"blocks": true,
		"items": false,
		"entities": false,
		"structures": false
  },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 3,
    // "title": "Useful Staffs",
		// "desc": "Adding new items in the game, each staff will have a unique ability. You can turn mobs into water, small trees, turn day into night, summon minions, and more!",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Vanilla Figurines",
		// "desc": "This adds decorative blocks that represent all vanilla mobs and their variants. The figurines can be crafted using a stonecutter.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Villajars",
		// "desc": "This adds a way to capture villagers in a jar and trade with them. The stationary entities should allow for more room and easier management.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // },
  // {
    // "dat_link": "link",
		// "res_link": "link",
		// "gallery": 0,
    // "title": "Xpiggy Bank",
		// "desc": "This adds a new block that lets you store yur XP as blocks. You can take your XP back by interacting with the blocks you receive from it.",
    // "full_desc": "Testing the full description lol",
		// "crafting": false,
		// "blocks": false,
		// "items": false,
		// "entities": false,
		// "structures": false
  // }
];